# necessary yml
language: r
cache: packages
sudo: required

# use bioconductor
bioc_required: true
bioc_use_devel: false

# notification setup
notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts
