# necessary yml
language: r
#cache: packages
#sudo: required

matrix:
  include:
    - stage: Bioconductor Release Testing
      r: bioc-release
    - stage: Bioconductor Devel Testing
      r: bioc-devel
    - stage: Test Running in Debug Mode
      r: release
      script: R -f inst/scripts/debugRuns.R

#cache:
#  - packages: true
#  - ccache

#addons:
#  apt:
#    packages:
#     - ccache

#before_install:
#  - mkdir -p $HOME/.R && echo -e 'VER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars



# use bioconductor
#bioc_required: true
#bioc_use_devel: false


# notification setup
notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts
