language: r
cache: packages

matrix:
  include:
    - stage: Bioconductor Release Testing
      r: bioc-release
    - stage: Bioconductor Devel Testing
      r: bioc-devel
    - stage: Test Running in Debug Mode
      install: R -e 'devtools::install_deps(dep = T, configure.args = c(debugMode = " --enable-debug " ))'
      script: R -f inst/scripts/debugRuns.R

notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts

#cache:
#  - packages: true
#  - ccache

#addons:
#  apt:
#    packages:
#     - ccache

#before_install:
#  - mkdir -p $HOME/.R && echo -e 'VER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
