language: r
cache: packages

matrix:
  fast_finish: true
  allow_failures:
    - stage: Linting
    - stage: Code Formatting
  include:
    #- stage: Bioconductor Release Testing
    #  r: bioc-release
    #- stage: Bioconductor Devel Testing
    #  r: bioc-devel
    - stage: Test Running in Debug Mode
      #before_install: mkdir -p $HOME/Rpackages
      #install: R -e 'devtools::install_deps(dep = T, configure.args = c(debugMode = " --enable-debug " ))'
      #install: R -e 'pkgLib=paste(Sys.getenv("HOME"), "/Rpackages", sep=""); install.packages("devtools", lib=pkgLib); devtools::install_deps(dep=TRUE, lib=pkgLib)'
      install:
        - R -e 'install.packages(c("BiocManager", "remotes"))'
        - R -e 'BiocManager::install("FertigLab/CoGAPS")'
        - R CMD build --no-build-vignettes .
        - R CMD INSTALL --configure-args="" *tar.gz
      script: R -f inst/scripts/debugRuns.R
    #- stage: Valgrind Analysis
    #  install: R -e 'install.packages("devtools"); devtools::install_deps(dep = T)'
    #  script: R -d valgrind -e 'library(CoGAPS); data(GIST); CoGAPS(GIST.matrix, nIterations=1000, outputFrequency=250)'
    - stage: Linting
      script: echo "linting not implemented"
    - stage: Code Formatting
      script: echo "formatting not implemented"

notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts

#cache:
#  - packages: true
#  - ccache

#addons:
#  apt:
#    packages:
#     - ccache

#before_install:
#  - mkdir -p $HOME/.R && echo -e 'VER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
