language: r
cache: packages
sudo: required

matrix:
  fast_finish: true
  allow_failures:
    - stage: Linting
    - stage: Code Formatting
  include:
    #- stage: Bioconductor Release Testing
    #  r: bioc-release
    #- stage: Bioconductor Devel Testing
    #  r: bioc-devel
    #- stage: Test Running in Debug Mode
    #  install:
    #    - R -e 'install.packages(c("BiocManager", "remotes"))'
    #    - R -e 'BiocManager::install("FertigLab/CoGAPS")'
    #    - R CMD build --no-build-vignettes .
    #    - R CMD INSTALL --configure-args=" --enable-debug " *tar.gz
    #  script: R -f inst/scripts/debugRuns.R
    - stage: Valgrind Analysis
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq valgrind
      install:
        - R -e 'install.packages(c("BiocManager", "remotes"))'
        - R -e 'BiocManager::install("FertigLab/CoGAPS")'
        - R CMD build --no-build-vignettes .
        - R CMD INSTALL *tar.gz
      script: R -d valgrind -e 'library(CoGAPS); data(GIST); CoGAPS(GIST.matrix, nIterations=1000, outputFrequency=250)'
    - stage: Linting
      script: echo "linting not implemented"
    - stage: Code Formatting
      script: echo "formatting not implemented"

notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts
