# necessary yml
language: r
sudo: required

# use bioconductor
bioc_required: true
bioc_use_devel: true

# test code coverage
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'

# notification setup
notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts
