# necessary yml
language: r
cache: packages
sudo: required

# test on both linux and OSX
os:
  - linux
  - osx

# use bioconductor
bioc_required: true
bioc_use_devel: true

# notification setup
notifications:
  slack: fertiglab:LZeNoaS7BnLfqP6XuHiDYdts
