# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_run <- function(y, treatStatus, timeRecorded, iter) {
    .Call('trans_test_run', PACKAGE = 'trans', y, treatStatus, timeRecorded, iter)
}

