// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cogapsMap
Rcpp::List cogapsMap(Rcpp::DataFrame DFrame, Rcpp::DataFrame SFrame, Rcpp::DataFrame FixedPatt, Rcpp::DataFrame ABinsFrame, Rcpp::DataFrame PBinsFrame, Rcpp::CharacterVector Config, Rcpp::NumericVector ConfigNums);
RcppExport SEXP _CoGAPS_cogapsMap(SEXP DFrameSEXP, SEXP SFrameSEXP, SEXP FixedPattSEXP, SEXP ABinsFrameSEXP, SEXP PBinsFrameSEXP, SEXP ConfigSEXP, SEXP ConfigNumsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DFrame(DFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type SFrame(SFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type FixedPatt(FixedPattSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ABinsFrame(ABinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type PBinsFrame(PBinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type Config(ConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ConfigNums(ConfigNumsSEXP);
    rcpp_result_gen = Rcpp::wrap(cogapsMap(DFrame, SFrame, FixedPatt, ABinsFrame, PBinsFrame, Config, ConfigNums));
    return rcpp_result_gen;
END_RCPP
}
// cogapsMapTest
Rcpp::List cogapsMapTest(Rcpp::DataFrame DFrame, Rcpp::DataFrame SFrame, Rcpp::DataFrame FixedPatt, Rcpp::DataFrame ABinsFrame, Rcpp::DataFrame PBinsFrame, Rcpp::CharacterVector Config, Rcpp::NumericVector ConfigNums);
RcppExport SEXP _CoGAPS_cogapsMapTest(SEXP DFrameSEXP, SEXP SFrameSEXP, SEXP FixedPattSEXP, SEXP ABinsFrameSEXP, SEXP PBinsFrameSEXP, SEXP ConfigSEXP, SEXP ConfigNumsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DFrame(DFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type SFrame(SFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type FixedPatt(FixedPattSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ABinsFrame(ABinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type PBinsFrame(PBinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type Config(ConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ConfigNums(ConfigNumsSEXP);
    rcpp_result_gen = Rcpp::wrap(cogapsMapTest(DFrame, SFrame, FixedPatt, ABinsFrame, PBinsFrame, Config, ConfigNums));
    return rcpp_result_gen;
END_RCPP
}
// cogaps
Rcpp::List cogaps(Rcpp::DataFrame DFrame, Rcpp::DataFrame SFrame, Rcpp::DataFrame ABinsFrame, Rcpp::DataFrame PBinsFrame, Rcpp::CharacterVector Config, Rcpp::NumericVector ConfigNums);
RcppExport SEXP _CoGAPS_cogaps(SEXP DFrameSEXP, SEXP SFrameSEXP, SEXP ABinsFrameSEXP, SEXP PBinsFrameSEXP, SEXP ConfigSEXP, SEXP ConfigNumsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DFrame(DFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type SFrame(SFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ABinsFrame(ABinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type PBinsFrame(PBinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type Config(ConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ConfigNums(ConfigNumsSEXP);
    rcpp_result_gen = Rcpp::wrap(cogaps(DFrame, SFrame, ABinsFrame, PBinsFrame, Config, ConfigNums));
    return rcpp_result_gen;
END_RCPP
}
// cogapsTest
Rcpp::List cogapsTest(Rcpp::DataFrame DFrame, Rcpp::DataFrame SFrame, Rcpp::DataFrame ABinsFrame, Rcpp::DataFrame PBinsFrame, Rcpp::CharacterVector Config, Rcpp::NumericVector ConfigNums);
RcppExport SEXP _CoGAPS_cogapsTest(SEXP DFrameSEXP, SEXP SFrameSEXP, SEXP ABinsFrameSEXP, SEXP PBinsFrameSEXP, SEXP ConfigSEXP, SEXP ConfigNumsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DFrame(DFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type SFrame(SFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ABinsFrame(ABinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type PBinsFrame(PBinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type Config(ConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ConfigNums(ConfigNumsSEXP);
    rcpp_result_gen = Rcpp::wrap(cogapsTest(DFrame, SFrame, ABinsFrame, PBinsFrame, Config, ConfigNums));
    return rcpp_result_gen;
END_RCPP
}
// cogapsTrans
Rcpp::List cogapsTrans(Rcpp::DataFrame DFrame, Rcpp::DataFrame SFrame, Rcpp::DataFrame FixedPatt, Rcpp::DataFrame ABinsFrame, Rcpp::DataFrame PBinsFrame, Rcpp::CharacterVector Config, Rcpp::NumericVector ConfigNums, std::vector<double> time_of_sample, std::vector<int> condition, Rcpp::NumericVector theta, int thin, std::string prior, std::string proposal, bool epsilon_mcmc, double delta, double epsilon, double epsilon_prior, double prior_mean, double prior_sd, bool fixedproposal, bool weightA);
RcppExport SEXP _CoGAPS_cogapsTrans(SEXP DFrameSEXP, SEXP SFrameSEXP, SEXP FixedPattSEXP, SEXP ABinsFrameSEXP, SEXP PBinsFrameSEXP, SEXP ConfigSEXP, SEXP ConfigNumsSEXP, SEXP time_of_sampleSEXP, SEXP conditionSEXP, SEXP thetaSEXP, SEXP thinSEXP, SEXP priorSEXP, SEXP proposalSEXP, SEXP epsilon_mcmcSEXP, SEXP deltaSEXP, SEXP epsilonSEXP, SEXP epsilon_priorSEXP, SEXP prior_meanSEXP, SEXP prior_sdSEXP, SEXP fixedproposalSEXP, SEXP weightASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DFrame(DFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type SFrame(SFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type FixedPatt(FixedPattSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ABinsFrame(ABinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type PBinsFrame(PBinsFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type Config(ConfigSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ConfigNums(ConfigNumsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type time_of_sample(time_of_sampleSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type condition(conditionSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< std::string >::type proposal(proposalSEXP);
    Rcpp::traits::input_parameter< bool >::type epsilon_mcmc(epsilon_mcmcSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_prior(epsilon_priorSEXP);
    Rcpp::traits::input_parameter< double >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< double >::type prior_sd(prior_sdSEXP);
    Rcpp::traits::input_parameter< bool >::type fixedproposal(fixedproposalSEXP);
    Rcpp::traits::input_parameter< bool >::type weightA(weightASEXP);
    rcpp_result_gen = Rcpp::wrap(cogapsTrans(DFrame, SFrame, FixedPatt, ABinsFrame, PBinsFrame, Config, ConfigNums, time_of_sample, condition, theta, thin, prior, proposal, epsilon_mcmc, delta, epsilon, epsilon_prior, prior_mean, prior_sd, fixedproposal, weightA));
    return rcpp_result_gen;
END_RCPP
}
// FixedMatrix
Rcpp::NumericMatrix FixedMatrix(Rcpp::NumericMatrix D, Rcpp::NumericMatrix A, Rcpp::NumericMatrix P, Rcpp::NumericVector T, int nSample, double delta, double epsilon, double prior_mean, double prior_sd, bool fixedproposal);
RcppExport SEXP _CoGAPS_FixedMatrix(SEXP DSEXP, SEXP ASEXP, SEXP PSEXP, SEXP TSEXP, SEXP nSampleSEXP, SEXP deltaSEXP, SEXP epsilonSEXP, SEXP prior_meanSEXP, SEXP prior_sdSEXP, SEXP fixedproposalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type nSample(nSampleSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< double >::type prior_sd(prior_sdSEXP);
    Rcpp::traits::input_parameter< bool >::type fixedproposal(fixedproposalSEXP);
    rcpp_result_gen = Rcpp::wrap(FixedMatrix(D, A, P, T, nSample, delta, epsilon, prior_mean, prior_sd, fixedproposal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CoGAPS_cogapsMap", (DL_FUNC) &_CoGAPS_cogapsMap, 7},
    {"_CoGAPS_cogapsMapTest", (DL_FUNC) &_CoGAPS_cogapsMapTest, 7},
    {"_CoGAPS_cogaps", (DL_FUNC) &_CoGAPS_cogaps, 6},
    {"_CoGAPS_cogapsTest", (DL_FUNC) &_CoGAPS_cogapsTest, 6},
    {"_CoGAPS_cogapsTrans", (DL_FUNC) &_CoGAPS_cogapsTrans, 21},
    {"_CoGAPS_FixedMatrix", (DL_FUNC) &_CoGAPS_FixedMatrix, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoGAPS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
